import { StateGraph, StateSchema, type GraphNode,START,END } from "@langchain/langgraph";
import { z } from "zod";
import {mistralAIModel , cohereModel , geminiModel} from './model.ai.js';
import {createAgent,ProviderStrategy,providerStrategy,HumanMessage} from "langchain";


const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().optional(),
    solution_2: z.string().optional(),
    judge:z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning:z.string().default(""),
        solution_2_reasoning:z.string().default(""),
    }),
})



const solutionNode : GraphNode<typeof state> = async (state) =>{
    const [mistralResponse,cohereResponse] = await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereModel.invoke(state.problem),
    ])
    return {
        solution_1: mistralResponse.content as string,
        solution_2: cohereResponse.content as string,
    }
}


const judgeNode : GraphNode<typeof state> = async (state)=>{

    const {problem,solution_1,solution_2} = state;

    const judge_node = createAgent({
        model:geminiModel,
        responseFormat:providerStrategy(z.object({
            solution_1_score:z.number().min(0).max(10),
            solution_2_score:z.number().min(0).max(10),
            solution_1_reasoning:z.string(),
            solution_2_reasoning:z.string(),
        })),
        systemPrompt:`You are judge tasked with evaluating two solutions generated by different AI models. Please provide score between 0-10 and reasoning for each solution.
        Problem: ${state.problem}
        Solution 1: ${state.solution_1}
        Solution 2: ${state.solution_2}
        `,
        tools:[],
    })

    const judgeResponse = await judge_node.invoke({
        messages:[new HumanMessage(`
            You are judge tasked with evalu ating two solutions generated by different AI models. Please provide score between 0-10 and reasoning for each solution.
            Problem: ${state.problem}
            Solution 1: ${state.solution_1}
            Solution 2: ${state.solution_2}
            
            `)]
    })

    const {solution_1_score,solution_2_score,solution_1_reasoning,solution_2_reasoning} = judgeResponse.structuredResponse;



    return {
        judge:{
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning,
        }
    }

}

const graph = new StateGraph(state)
    .addNode("solutions",solutionNode)
    .addNode("judge_node",judgeNode)
    .addEdge(START,"solutions")
    .addEdge("solutions","judge_node")
    .addEdge("judge_node",END)
    .compile()

export default async function runGraph(problem:string){
    const result = await graph.invoke({
        problem,
    });

    return result;
}

